### ISSUE TITLE
export_to_file function (and may be other also) does not work when specifying --path in plackup

### ISSUE THREAD

**Issue by moussaid521** [vanstyn/RapidApp#172]
Hi,

When we specify a URL base in --path option in plackup (*) ,  everything seems working fine
![image](https://cloud.githubusercontent.com/assets/18347563/20222534/b694dde6-a846-11e6-9cc7-b7070eae634e.png)

 except  the export_to_file function does not work, it seems not to taking in consideration this option.
it gives the following error in the debug monitor, but nothing in the browser , just does not export silently: (here applied in the creatureZoo app)
"POST /main/db/db_creature/export_to_file HTTP/1.1" 404 9 "http://localhost:2250/creatureZoo/" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.87 Safari/537.36"

(*) The command used to launch the app: ~/yn2015/CreatureZoo$ **plackup -r --path /creatureZoo**

**Comment by vanstyn** [comment]
@moussaid521 -

Thank you for the report. This was indeed a bug, which has now been fixed (see bf9d573). I am planning on making a new CPAN release with this fix by the end of the week.
