### ISSUE TITLE
possible typo in Line 66 in Catalyst::Plugin::RapidApp::RapidDbic ?

### ISSUE THREAD

**Issue by moussaid521** [vanstyn/RapidApp#173]
Hi,

I was just exploring the Plugins and noticed a possible typo in line 66 of the file ..\RapidApp\lib\Catalyst\Plugin\RapidApp\RapidDbic.pm

setup_component does not seem to exist anywhere else, did you mean before 'setup_finalize' may be?

**Comment by vanstyn** [comment]
The method ```setup_component``` is in Catalyst, so no, it is not a typo:

https://metacpan.org/source/JJNAPIORK/Catalyst-Runtime-5.90112/lib/Catalyst.pm#L3192
