### ISSUE TITLE
defined views does not work if you set a module_root_namespace.

### ISSUE THREAD

**Issue by moussaid521** [vanstyn/RapidApp#174]
Hi,

If we create some views then we change the module_root_namespace, the old views does not work, and it gives an error about root_template_prefix not being defined. Is this the intended behavior?
here in the image an example with the creatureZoo app, when we add :  
module_root_namespace => 'CreatureZoo',
in the RapidApp module  configuration.
![image](https://cloud.githubusercontent.com/assets/18347563/20306088/bf355448-ab49-11e6-9b67-3f638e51e319.png)

**Comment by vanstyn** [comment]
This is a known limitation. Since saved views store the url, if the url is changed, the view has to be recreated.
