### ISSUE TITLE
invalid prereq on DBIx::Class::_Util

### ISSUE THREAD

**Issue by haarg** [vanstyn/RapidApp#176]
There is a dependency on `DBIx::Class::_Util` that is listed in the metadata for this dist, but that module is not indexed on PAUSE so it can't be resolved.  In many cases this won't cause issues because the module will be available once `DBIx::Class` is installed, but depending on how the dependencies are resolved it can cause failures.

It's probably not good to be using the module at all, but it definitely should not be listed in the prerequisites.

**Comment by kentfredric** [comment]
This looks like a dependency that was added by Dist::Zilla::Plugin::AutoPrereqs, to add insult to injury. The dep isn't included [statically in dist.ini](https://github.com/vanstyn/RapidApp/blob/master/dist.ini#L53)

This obviously needs another `skip = ` rule, but AutoPrereqs automatically depending on things with `::_` components is a potentially dubious choice as well.
