### ISSUE TITLE
Exception on incorrect password

### ISSUE THREAD

**Issue by sammakkoinen** [vanstyn/RapidApp#183]
1) Install RapidApp and DBD::mysql with cpanm (I have tested on perlbrew with perls 5.24.2 and 5.30.3). (This installs Catalyst 5.90126.)
2) Create an app with `rapidapp.pl --helpers RapidDbic,Templates,TabGui,AuthCore,NavCore TestApp -- --dsn dbi:mysql:database=DBNAME,root,''`, where DBNAME is any existing MySQL DB
3) cd TestApp; perl Makefile.PL
4) Start the app with `./script/testapp_server.pl`
5) Go to http://localhost:3000/ and try to log in with incorrect credentials: admin:test (instead of admin:pass)
6) The result is a server error page with the following exception:
`Caught exception in TestApp::Controller::Auth->login "Can't call method "username" on an undefined value at /home/rp/perl5/perlbrew/perls/perl-5.30.3/lib/site_perl/5.30.3/Catalyst/Plugin/RapidApp/AuthCore.pm line 255."`

**Comment by vanstyn** [comment]
will be fixed in 1.3202 shipping to cpan momentarily.

Thanks
