### ISSUE TITLE
http://www.rapidapp.info/ not secure. https://www.rapidapp.info/ has invalid certificate

### ISSUE THREAD

**Issue by tehmoth** [vanstyn/RapidApp#197]
http://www.rapidapp.info/ is http-only, and https://www.rapidapp.info/ version redirects back to http://www.rapidapp.info/ but has an invalid certificate (for intellitree.com): 

see https://www.ssllabs.com/ssltest/analyze.html?d=www.rapidapp.info&hideResults=on

**Comment by vanstyn** [comment]
fixed a long time ago
