### ISSUE TITLE
Convert from Moose to Moo

### ISSUE THREAD

**Issue by vanstyn** [vanstyn/RapidApp#75]
Preliminary find/replace commands

```bash
# Direct conversions:
find lib/RapidApp/ -type f -exec sed -i \
  's/use Moose\;/use Moo\;/g' {} \;
  
find lib/RapidApp/ -type f -exec sed -i \
  's/use Moose::Role\;/use Moo::Role\;/g' {} \;
  
find lib/RapidApp/ -type f -exec sed -i \
  's/use MooseX::Traits\;/use MooX::Traits\;/g' {} \;

  
# Removals:
find lib/RapidApp/ -type f -exec sed -i \
  's/use MooseX::MarkAsMethods\;//g' {} \;
  
find lib/RapidApp/ -type f -exec sed -i \
  's/use MooseX::NonMoose\;//g' {} \;
  
find lib/RapidApp/ -type f -exec sed -i \
  's/no Moose\;//g' {} \;

find lib/RapidApp/ -type f -exec sed -i \
  's/__PACKAGE__->meta->make_immutable\;//g' {} \;

# make_immutable stragglers (comment-out)
find lib/RapidApp/ -type f -exec sed -i \
  's/__PACKAGE__->meta->make_immutable/\#__PACKAGE__->meta->make_immutable/g' {} \;
```

**Comment by vanstyn** [comment]
### convert progress

The ```devel/convert_to_moo.pl``` script does a lot of the simple code transforms now. The current blockers are the attrs with traits, such as ```Array``` and ```Hash``` native delegations. This will probably be handled by ```MooX::HandlesVia```

But, the other item that will have to be addressed is the current usage of ```RapidApp::Role::PerRequestBuildDefReset``` which is currently used as a trait to flag attrs for clearing. I want to unfactor this stuff anyway, so I am going to put this task on the shelf for a while and come back to it after that stuff has been removed. Then there shouldn't be too many remaining items blocking full conversion to Moo (that I know of anyway)

**Comment by silverdirk** [comment]
BTW, check out Catalyst::Component::InstancePerContext if you haven't seen it yet.  Its implementation is what I think you were looking for originally when you wanted to have lazy-built attributes on controllers/modules.

The idea is you just clone the controller when accessed the first time for a request, and then store it in the stash for the remainder of the request.

**Comment by vanstyn** [comment]
As of now, I don't think we'll be moving forward with this conversion after all. We have started taking advantage of more Moose meta capabilities, and I think this is worthwhile...
