### ISSUE TITLE
"null or empty" MultiFilters throw exception (_binary_op_fuser limitation)

### ISSUE THREAD

**Issue by vanstyn** [vanstyn/RapidApp#89]
The "null or empty" MultiFilter conditions apparently are broken since switching to use `_binary_op_fuser()` to generate them. There are generated in this form:

``` perl
'foo', [{'='=>''},{'='=>undef}]
```

The `_binary_op_fuser()` is returning like this:

``` perl
\[
    "foo   (= ?) OR  IS NULL ",
    [{},"" ]
]
```

Notify: @ribasushi

**Comment by ribasushi** [comment]
@vanstyn Hmmm... revisiting this (without having the context of _b_o_f) I am now unsure why this was an issue at all. Consider:

```
perl -MSQL::Abstract -MDevel::Dwarn -e 'Dwarn [
  SQL::Abstract->new->where(
    { foo => [
      { "=" => ''},
      { "=" => undef }
    ] }
  )
]'

[
  " WHERE ( ( foo IS NULL OR foo IS NULL ) )"
]

```

What did I miss...?

**Comment by vanstyn** [comment]
@ribasushi - I *think* what you might be missing is the case when 'foo' is a more complex $lhs argument (hence the need for ```_binary_op_fuser``` in the first place)
