### ISSUE TITLE
Multi-rel column counts ignore 'where' in relationship attr

### ISSUE THREAD

**Issue by vanstyn** [vanstyn/RapidApp#95]
Regression which started with 0be555eac684 after the refactor to use CorrelateRelationship

**Comment by ribasushi** [comment]
Deliberations on this issue are still ongoing. A big chunk of the work will likely resolve due to a conversation on Jan 31st. More updates in the first/second week of Feb.

**Comment by vanstyn** [comment]
Since code is working now as-is, I'm closing. We will revisit when DBIC changes are made, which at that point will be a code cleanup to make use of updated APIs (once they are available)

**Comment by ribasushi** [comment]
o/ @vanstyn
I finally arrived at this spot from a different side, with more context to help me see how to actually tackle this. As an extra sanity check I need to recreate your original problem within rapidapp. Can you provide me with the exact commitish which exhibited the *oh noes `where` doesn't work*, and a pointer to a minimal test (which I hope you have somewhere in the repo) demonstrating a failure?

Cheers

**Comment by vanstyn** [comment]
It stopped working when I did the refactor in this commit (also listed in the body/first comment):

https://github.com/vanstyn/RapidApp/commit/0be555eac68471145d66dff194560df3761c7137

I switched to try to use 'correlate' to follow the more correct API, but that broke 'where' and I had to switch back (and silence the warning DBIC start throwing)

**Comment by ribasushi** [comment]
@vanstyn What I meant is - which test (as in `<something>.t`) can I run to see the ` but that broke 'where' ` part

**Comment by vanstyn** [comment]
Just closing the loop from IRC ... there isn't a RapidApp test case for this, but @ribasushi will send me a tarball with his prospective fix and I will manually test it
